# This is a basic workflow to help you get started with Actions

name: Test B

on:
  workflow_run:
    workflows:
      - Test A

jobs:
  testJob:
    name: Test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - id: set_var
        run: |
          content= cat ./data.json
          echo "::set-output name=packageJson::$content"
      - run: |
          echo "${{packageJson}
          echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"
