name: Testing Report Activity
on:
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: EleonoraBorzis/repo-activity-report-action@Finaltouches
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-name:  EleonoraBorzis/group-composition-action
          issue-number: 10
